data:
  balance_dataset: true
  lowercase: true
  max_length: 50
  max_samples: 20000
  min_text_length: 2
  min_vocab_freq: 1
  positive_ratio: 0.5
  remove_hashtags: false
  remove_mentions: false
  remove_numbers: false
  remove_punctuation: false
  remove_urls: true
  test_split: 0.15
  train_split: 0.7
  val_split: 0.15
  vocab_size_limit: 5000
evaluation:
  compute_accuracy: true
  compute_auc_pr: false
  compute_auc_roc: false
  compute_confusion_matrix: true
  compute_f1_score: true
  compute_precision: true
  compute_recall: true
  compute_sensitivity: false
  compute_specificity: false
  plot_attention_visualization: false
  plot_confusion_matrix: true
  plot_precision_recall_curve: false
  plot_roc_curve: false
  plot_training_history: true
  primary_metric: f1_score
  save_best_model: false
  save_final_test: true
  save_per_epoch: false
hardware:
  auto_memory_management: true
  cleanup_every_n_batches: 20
  dataloader_workers: 2
  dynamic_batch_size: true
  force_gc_every_epoch: true
  max_batch_size: 32
  memory_threshold: 0.6
  min_batch_size: 8
  mixed_precision: false
  pin_memory: false
hyperparameter_tuning:
  batch_sizes:
  - 8
  - 16
  classifier_architectures:
  - - 32
    - 16
  - - 16
  dropout_values:
  - 0.1
  - 0.2
  - 0.3
  embedding_dims:
  - 32
  - 64
  enabled: true
  grid_search_params: {}
  hidden_dims:
  - 16
  - 32
  learning_rates:
  - 0.01
  - 0.001
  method: random_search
  n_random_samples: 15
  n_trials: 15
  num_layers_options:
  - 1
  - 2
  optimizer_types:
  - adam
  timeout: 600
  use_attention_options:
  - false
  weight_decays:
  - 1e-4
  - 1e-3
model:
  bidirectional: true
  classifier_activation: relu
  classifier_final_dropout: 0.2
  classifier_hidden_layers:
  - 32
  - 16
  classifier_use_batch_norm: true
  dropout: 0.2
  embedding_dim: 32
  hidden_dim: 32
  max_grad_norm: 1.0
  num_layers: 1
  use_attention: false
  use_attention_pooling: false
  use_batch_norm: true
  use_gradient_clipping: true
  use_last_hidden: true
  use_max_pooling: true
  use_mean_pooling: true
paths:
  best_model_file: best_model_dev.pth
  config_file: config_dev.yaml
  data_dir: data_dev
  logs_dir: logs_dev
  models_dir: models_dev
  plots_dir: plots_dev
  results_dir: results_dev
  study_file: optuna_study_dev.db
  tuning_results_dir: hyperparameter_tuning_dev
  vocabulary_file: vocabulary_dev.pkl
project:
  author: AI Assistant
  description: Configurazione per test rapidi e sviluppo
  name: tweet-sentiment-analysis-dev
  version: 2.0.0-dev
training:
  adam_betas:
  - 0.9
  - 0.999
  adam_eps: 1e-8
  batch_size: 8
  cosine_T_max: 100
  cosine_eta_min: 1.0e-06
  early_stopping_enabled: true
  early_stopping_metric: f1_score
  early_stopping_min_delta: 0.001
  early_stopping_patience: 5
  gradient_accumulation_steps: 1
  keep_last_n: 1
  learning_rate: 0.01
  num_epochs: 10
  optimizer_type: adam
  save_best: true
  save_every_n_epochs: 999
  scheduler_factor: 0.8
  scheduler_min_lr: 1e-5
  scheduler_mode: max
  scheduler_patience: 3
  scheduler_type: reduce_on_plateau
  sgd_momentum: 0.9
  sgd_nesterov: true
  weight_decay: 1e-4
