# =============================================================================
# CONFIGURAZIONE SVILUPPO - TEST RAPIDO HYPERPARAMETER TUNING
# =============================================================================

# Informazioni progetto
project:
  name: "tweet-sentiment-analysis-dev"
  version: "2.0.0-dev"
  description: "Configurazione per test rapidi e sviluppo"
  author: "AI Assistant"

# Dataset ridotto per test rapidi
data:
  max_samples: 1000                     # Ridotto per test veloce
  max_length: 50                        # Sequenze più corte
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  min_vocab_freq: 1                     # Meno restrittivo
  vocab_size_limit: 5000                # Vocabolario ridotto
  balance_dataset: true
  positive_ratio: 0.5
  
  # Preprocessing semplificato
  preprocessing:
    remove_urls: true
    remove_mentions: false
    remove_hashtags: false
    lowercase: true
    remove_punctuation: false
    remove_numbers: false
    min_text_length: 2

# Modello semplificato per test
model:
  embedding_dim: 64                     # Ridotto per velocità
  hidden_dim: 32                        # Ridotto per velocità
  num_layers: 1                         # Solo 1 layer
  dropout: 0.2
  bidirectional: true
  use_attention: false                  # Disabilitato per velocità
  use_batch_norm: true
  use_gradient_clipping: true
  max_grad_norm: 1.0
  
  # Classificatore semplice
  classifier:
    hidden_layers: [32, 16]             # Più piccolo
    activation: "relu"
    use_batch_norm: true
    final_dropout: 0.2
  
  # Pooling ridotto
  pooling:
    use_max_pooling: true
    use_mean_pooling: true
    use_last_hidden: true
    use_attention_pooling: false        # Disabilitato

# Training veloce
training:
  num_epochs: 10                        # Pochissime epoche per test
  batch_size: 16                        # Batch piccolo
  learning_rate: 0.01                   # LR più alto per convergenza veloce
  weight_decay: 1e-4
  gradient_accumulation_steps: 1
  
  # Ottimizzatore
  optimizer:
    type: "adam"
    adam:
      betas: [0.9, 0.999]
      eps: 1e-8
  
  # Scheduler aggressivo
  scheduler:
    type: "reduce_on_plateau"
    reduce_on_plateau:
      mode: "max"
      factor: 0.8                       # Riduzione più aggressiva
      patience: 3                       # Pazienza ridotta
      min_lr: 1e-5
  
  # Early stopping veloce
  early_stopping:
    enabled: true
    patience: 5                         # Pazienza molto ridotta
    metric: "f1_score"
    min_delta: 0.001
  
  # Checkpoint ridotti
  checkpointing:
    save_best: true
    save_every_n_epochs: 999            # Quasi mai (solo per test)
    keep_last_n: 1

# Hardware ottimizzato per sviluppo
hardware:
  auto_memory_management: true
  memory_threshold: 0.6                 # Usa meno memoria
  dynamic_batch_size: true
  min_batch_size: 8
  max_batch_size: 32                    # Limitato per stabilità
  mixed_precision: false
  dataloader_workers: 2                 # Ridotto
  pin_memory: false                     # Disabilitato per compatibilità
  cleanup_every_n_batches: 20          # Più frequente
  force_gc_every_epoch: true

# Metriche essenziali
evaluation:
  primary_metric: "f1_score"
  
  # Solo metriche essenziali
  metrics:
    accuracy: true
    precision: true
    recall: true
    f1_score: true
    auc_roc: false                      # Disabilitato per velocità
    auc_pr: false                       # Disabilitato per velocità
    confusion_matrix: true
    sensitivity: false
    specificity: false
  
  # Plot ridotti
  plots:
    confusion_matrix: true
    roc_curve: false
    precision_recall_curve: false
    training_history: true
    attention_visualization: false
  
  # Report minimali
  detailed_reports:
    save_per_epoch: false
    save_best_model: false              # Riduce I/O
    save_final_test: true

# Hyperparameter tuning per test rapidi
hyperparameter_tuning:
  enabled: true                         # Abilitato per test
  method: "random_search"               # Più veloce di Optuna per test
  n_trials: 15                          # Pochi trial per test veloce
  timeout: 600                          # 10 minuti max
  
  # Spazio di ricerca ridotto
  search_space:
    embedding_dim: [32, 64]             # Solo 2 opzioni
    hidden_dim: [16, 32]                # Solo 2 opzioni
    num_layers: [1, 2]                  # Solo 2 opzioni
    dropout: [0.1, 0.2, 0.3]            # 3 opzioni
    learning_rate: [0.01, 0.001]        # Solo 2 opzioni
    batch_size: [8, 16]                 # Solo 2 opzioni
    optimizer_type: ["adam"]            # Solo Adam
    weight_decay: [1e-4, 1e-3]          # Solo 2 opzioni
    use_attention: [false]              # Solo senza attention per velocità
    classifier_layers: [[32, 16], [16]] # Solo 2 architetture
  
  # Random search per test
  random_search:
    n_random_samples: 15                # Coincide con n_trials

# Logging ridotto
logging:
  level: "INFO"
  log_to_file: false                    # No file per test
  log_metrics_every_n_epochs: 1
  log_memory_usage: false               # Riduce overhead
  use_tensorboard: false
  use_wandb: false
  plot_every_n_epochs: 999             # Mai durante training

# Paths per sviluppo
paths:
  data_dir: "data_dev"
  models_dir: "models_dev"
  logs_dir: "logs_dev"
  plots_dir: "plots_dev"
  results_dir: "results_dev"
  vocabulary_file: "vocabulary_dev.pkl"
  best_model_file: "best_model_dev.pth"
  config_file: "config_dev.yaml"
  tuning_results_dir: "hyperparameter_tuning_dev"
  study_file: "optuna_study_dev.db"

# Test essenziali
testing:
  batch_size: 16
  save_predictions: false               # Riduce I/O
  save_probabilities: false            # Riduce I/O
  
  interactive:
    show_attention: false               # Disabilitato
    show_confidence: true
    show_preprocessing: false
  
  example_tests:
    enabled: false                      # Disabilitato per velocità
    save_results: false
    
  edge_case_testing:
    enabled: false                      # Disabilitato per velocità
    comprehensive: false
    save_report: false

# Riproducibilità
reproducibility:
  seed: 42
  deterministic: false                  # Disabilitato per velocità
  benchmark: true                       # Abilitato per velocità

# Debug abilitato
debug:
  enabled: true                         # Modalità debug attiva
  fast_dev_run: true                    # Run veloce
  save_intermediate_outputs: false
  profiling: false
  
  # Configurazione test rapido
  fast_run:
    max_samples: 500                    # Ancora meno campioni
    num_epochs: 5                       # Ancora meno epoche
    batch_size: 8                       # Batch ancora più piccolo 